general {
  # avoid starting multiple hyprlock instances
  lock_cmd = pidof hyprlock || hyprlock
  # lock before suspend
  before_sleep_cmd = loginctl lock-session
  # screen on after suspend
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' && systemctl --user restart wlsunset
}

listener {
  timeout = 300 # 5 min
  # screen off when timeout has passed
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
  # screen on when activity is detected after timeout has fired
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
  timeout = 302
  on-timeout = loginctl lock-session
}

listener {
  timeout = 900
  on-timeout = systemctl suspend
}
